spring:

  h2:
    console:
      enabled: true
      path: /console

  datasource:
    platform: h2
    data: classpath*:db/h2/data.sql
    schema: classpath*:db/h2/schema.sql

  jpa:
    hibernate:
      ddl-auto: update

  resources:
    static-locations: "file:webapp/src/,file:webapp/bower_components/"

  devtools:
    restart:
      additional-paths: "webapp/src/,webapp/bower_components/"
      additional-exclude: "**/*.html,**/*.js,**/*.css"

  thymeleaf:
    cache: false

resources:
  avatar-folder: images/avatars/

remember-me:
  token: SN_REMEMBER_TOKEN
  cookie: SN_REMEMBER_ME_COOKIE

debug: true





