logging:
  level:
    org.springframework.web.client.RestTemplate: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.apache.http: debug

spring:

  h2:
    console:
      enabled: true
      path: /console

  devtools:
    restart:
      additional-paths: "webapp/src/,webapp/bower_components/"
      additional-exclude: "**/*.html,**/*.js,**/*.css"

#debug: true